#!/bin/bash


startup_check() {
    # Ensure root user is not running the script
    if [ "$EUID" = 0 ]; then
        clear
        cat << EOF
*** You are attempting to run this script as root user ***

This is poor practice,
please try again as a created user with sudo privledges

EOF
        exit
    fi

    # Ensure needed programs are installed
    if ! command -v jq &> /dev/null; then
        clear
        echo "jq is not installed, please refer to README for dependency list"
        exit
    elif ! command -v curl &> /dev/null; then
        clear
        echo "curl is not installed, please refer to README for dependency list"
        exit
    elif ! command -v wget &> /dev/null; then
        clear
        echo "wget is not installed, please refer to README for dependency list"
        exit
    elif ! command -v xxd &> /dev/null; then
        clear
        echo "xxd is not installed, please refer to README for dependency list"
        exit
    fi
}

startup_check
sudo systemctl stop und

mv $HOME/.und_mainchain/data/priv_validator_state.json $HOME/.und_mainchain/priv_validator_state.json
rm -rf $HOME/.und_mainchain/data/*
rm -rf $HOME/.und_mainchain/config/addrbook.json
mv $HOME/.und_mainchain/priv_validator_state.json $HOME/.und_mainchain/data/priv_validator_state.json

HANDH_URL=https://rest.unification.io/cosmos/base/tendermint/v1beta1/blocks/latest
HANDH=$(curl -s $HANDH_URL)
HEIGHT=$(echo $HANDH | jq -r '.block.header.height')
HASH=$(echo $HANDH | jq -r '.block_id.hash' | base64 -d | xxd -p -u -c 50)

sed -i "s/trust_height.*/trust_height = $HEIGHT/" $HOME/.und_mainchain/config/config.toml
sed -i 's/trust_hash.*/trust_hash = "'$HASH'"/' $HOME/.und_mainchain/config/config.toml

sudo systemctl restart und
sudo journalctl -u und -f -o cat
